const mongoose = require('mongoose');

const applicationSchema = new mongoose.Schema(
  {
    job: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Job',
      required: false,
    },
    jobCode: { type: String, default: '' },
    jobTitle: { type: String, default: '' },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    name: { type: String, required: true },
    email: { type: String, required: true },
    phone: String,
    resume: { type: String, required: true },
    coverLetter: String,
    experience: String,
    course: String,
    currentCompany: String,
    expectedSalary: String,
    status: {
      type: String,
      enum: [
        'Pending',
        'Under Review',
        'Shortlisted',
        'Interview',
        'Selected',
        'Offer',
        'Document Verification',
        'Joining',
        'Onboarded',
        'HR Verification',
        'HR Approval',
        'Accepted',
        'Rejected',
      ],
      default: 'Pending',
    },
    notes: String,
    reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    // Selection Confirmation
    interviewDate: Date,
    selectionStatus: { type: String, default: '' },
    joiningDate: Date,
    reportingManager: String,
    workLocation: { type: String, default: 'Bareilly / Hybrid' },
    employmentType: {
      type: String,
      enum: ['Full-time', 'Part-time', 'Internship', 'Contract', ''],
      default: '',
    },
    departmentSelected: String,
    positionSelected: String,
    offerPackage: String,
    ctc: String,
    workingHours: { type: String, default: '9:30 AM – 6:30 PM' },
    probationPeriod: { type: String, default: '3 months' },
    noticePeriod: { type: String, default: '30 days' },
    offerAccepted: { type: Boolean, default: false },
    offerRejected: { type: Boolean, default: false },
    offerRespondedAt: Date,
    // Employee Joining Form
    joiningForm: {
      // Step 1 Personal
      firstName: String,
      middleName: String,
      lastName: String,
      parentName: String,
      dateOfBirth: Date,
      gender: String,
      bloodGroup: String,
      maritalStatus: String,
      nationality: { type: String, default: 'Indian' },
      profilePhoto: String,
      // Step 2 Contact
      mobile: String,
      alternateMobile: String,
      personalEmail: String,
      currentAddress: String,
      permanentAddress: String,
      city: String,
      state: String,
      pinCode: String,
      emergencyContactName: String,
      emergencyContactNumber: String,
      emergencyContactRelation: String,
      formStepCompleted: { type: Number, default: 0 },
      // Step 3 Education
      educationRecords: [
        {
          qualification: String,
          institute: String,
          boardUniversity: String,
          passingYear: String,
          percentageCgpa: String,
        },
      ],
      // Step 4 Employment
      isFresher: { type: Boolean, default: false },
      bankDetails: {
        accountHolderName: String,
        bankName: String,
        accountNumber: String,
        ifsc: String,
        branch: String,
        accountType: String,
      },
      nominee: {
        name: String,
        relation: String,
        phone: String,
        address: String,
        sharePercent: String,
      },
      policiesAccepted: {
        codeOfConduct: { type: Boolean, default: false },
        dataPrivacy: { type: Boolean, default: false },
        attendancePolicy: { type: Boolean, default: false },
        leavePolicy: { type: Boolean, default: false },
      },
      declaration: {
        agreed: { type: Boolean, default: false },
        eSignName: String,
        eSignDate: Date,
        place: String,
      },
      hrVerification: {
        personalOk: { type: Boolean, default: false },
        documentsOk: { type: Boolean, default: false },
        bankOk: { type: Boolean, default: false },
        approved: { type: Boolean, default: false },
        approvedBy: String,
        approvedAt: Date,
        remarks: String,
      },
      generatedEmployeeId: String,
      employeeAccountCreated: { type: Boolean, default: false },
      joiningConfirmed: { type: Boolean, default: false },
      verificationDocuments: [
        {
          category: String,
          name: String,
          fileUrl: String,
          status: {
            type: String,
            enum: ['Pending', 'Under Review', 'Verified', 'Rejected'],
            default: 'Pending',
          },
          remarks: String,
        },
      ],
      previousEmployment: [
        {
          company: String,
          designation: String,
          department: String,
          joiningDate: String,
          leavingDate: String,
          lastSalary: String,
          experience: String,
          reasonForLeaving: String,
          previousEmployeeId: String,
          experienceLetter: String,
        },
      ],
    },
    // Pipeline tracking
    pipelineStep: {
      type: String,
      enum: [
        '',
        'Interview',
        'Selection',
        'Offer',
        'Employee Form',
        'Document Verification',
        'Joining',
        'Employee ID',
        'Onboarding',
        'Completed',
      ],
      default: '',
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Application', applicationSchema);
